package demos;

/*
 * MIT License
 *
 * Copyright (c) 2009-2016 Ignacio Calderon <https://github.com/kronenthaler>
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * @author kronenthaler
 */
public class Examples extends javax.swing.JFrame {

	/**
	 * Creates new form Examples
	 */
	public Examples() {
		initComponents();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String[] args) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new Examples().setVisible(true);
			}
		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		javax.swing.JTabbedPane jTabbedPane2 = new javax.swing.JTabbedPane();
		demos.fuzzy.FuzzyPanel fuzzyPanel1 = new demos.fuzzy.FuzzyPanel();
		javax.swing.JTabbedPane jTabbedPane3 = new javax.swing.JTabbedPane();
		demos.genetic.BinaryPanel binaryPanel1 = new demos.genetic.BinaryPanel();
		demos.genetic.Permutation permutation1 = new demos.genetic.Permutation();
		javax.swing.JTabbedPane jTabbedPane1 = new javax.swing.JTabbedPane();
		demos.nn.PerceptronPanel perceptronPanel1 = new demos.nn.PerceptronPanel();
		demos.nn.MPLPanel mPLPanel1 = new demos.nn.MPLPanel();
		demos.nn.RBFPanel rBFPanel1 = new demos.nn.RBFPanel();
		demos.nn.LVQPanel lVQPanel1 = new demos.nn.LVQPanel();
		demos.nn.SVMPanel sVMPanel1 = new demos.nn.SVMPanel();
		demos.nn.KohonenPanel kohonenPanel1 = new demos.nn.KohonenPanel();
		demos.nn.CompetitivePanel competitivePanel1 = new demos.nn.CompetitivePanel();
		demos.nn.HopfieldPanel hebbPanel1 = new demos.nn.HopfieldPanel();
		javax.swing.JTabbedPane jTabbedPane4 = new javax.swing.JTabbedPane();
		demos.search.BFSPanel bFSPanel1 = new demos.search.BFSPanel();
		demos.search.DFSPanel dFSPanel1 = new demos.search.DFSPanel();
		// Variables declaration - do not modify//GEN-BEGIN:variables
		demos.search.AStarPanel aStarPanel1 = new demos.search.AStarPanel();
		demos.trees.TreesPanel treesPanel1 = new demos.trees.TreesPanel();
		javax.swing.JTabbedPane jTabbedPane5 = new javax.swing.JTabbedPane();
		demos.ants.AntSystemPanel antSystemPanel1 = new demos.ants.AntSystemPanel();
		demos.ants.AntColonySystemPanel antColonySystemPanel1 = new demos.ants.AntColonySystemPanel();
		demos.ants.AntSystemRankPanel antSystemRankPanel1 = new demos.ants.AntSystemRankPanel();
		demos.ants.ElitistAntSystemPanel elitistAntSystemPanel1 = new demos.ants.ElitistAntSystemPanel();
		demos.ants.AntQPanel antQPanel1 = new demos.ants.AntQPanel();
		demos.ants.MMASPanel mMASPanel1 = new demos.ants.MMASPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Examples libai");

		jTabbedPane2.addTab("Fuzzy", fuzzyPanel1);

		jTabbedPane3.addTab("Binary", binaryPanel1);
		jTabbedPane3.addTab("Permutation", permutation1);

		jTabbedPane2.addTab("Genetic", jTabbedPane3);

		jTabbedPane1.addTab("Adaline", perceptronPanel1);
		jTabbedPane1.addTab("MultiLayerPerceptron", mPLPanel1);
		jTabbedPane1.addTab("RadialBasisFunction", rBFPanel1);
		jTabbedPane1.addTab("LearningVectorQuantization", lVQPanel1);
		jTabbedPane1.addTab("SupportVectorMachine", sVMPanel1);
		jTabbedPane1.addTab("Kohonen", kohonenPanel1);
		jTabbedPane1.addTab("Competitive", competitivePanel1);
		jTabbedPane1.addTab("Hopfield", hebbPanel1);

		jTabbedPane2.addTab("Neural Networks", jTabbedPane1);

		jTabbedPane4.addTab("BreadthFirstSearch", bFSPanel1);
		jTabbedPane4.addTab("DepthFirstSearch", dFSPanel1);
		jTabbedPane4.addTab("A*", aStarPanel1);

		jTabbedPane2.addTab("Search", jTabbedPane4);

		treesPanel1.setEnabled(false);

		javax.swing.GroupLayout treesPanel1Layout = new javax.swing.GroupLayout(treesPanel1);
		treesPanel1.setLayout(treesPanel1Layout);
		treesPanel1Layout.setHorizontalGroup(
				treesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 634, Short.MAX_VALUE)
		);
		treesPanel1Layout.setVerticalGroup(
				treesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 491, Short.MAX_VALUE)
		);

		jTabbedPane2.addTab("Decision Trees", treesPanel1);

		jTabbedPane5.addTab("AntSystem", antSystemPanel1);
		jTabbedPane5.addTab("AntColonySystem", antColonySystemPanel1);
		jTabbedPane5.addTab("AntSystemRank", antSystemRankPanel1);
		jTabbedPane5.addTab("ElististAntSystem", elitistAntSystemPanel1);
		jTabbedPane5.addTab("AntQ", antQPanel1);
		jTabbedPane5.addTab("MMAS", mMASPanel1);

		jTabbedPane2.addTab("Ants", jTabbedPane5);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jTabbedPane2)
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jTabbedPane2)
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents
	// End of variables declaration//GEN-END:variables
}
